global:
  dockerRegistry: registry.hub.docker.com/raresociopath
  dockerRegistryCredentialsId: rs-docker-hub

  scmServer: github.com
  scmGroup: raresociopath
  defaultBranch: master
  defaultNamespace: raresociopath

  repositories:
    - name: rs-jenkins-jobs
      humanName: "Jenkins Jobs"
    - name: rs-hello-world
      humanName: "Hello World Application"
      language: simple
