jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: ion
          password: ion

  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Overall/Read:anonymous"
        - "Overall/Administer:authenticated"
unclassified:
  simple-theme-plugin:
    elements:
      - cssUrl:
          url: "https://fishi.devtail.io/content-images/jenkins-devtail-theme.css"
