jenkins:
  systemMessage: "RS Jenkins"
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: admin
          password: admin

  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Overall/Read:anonymous"
        - "Overall/Administer:authenticated"
security:
  globalJobDslSecurityConfiguration:
    useScriptSecurity: false
credentials:
  system:
    domainCredentials:
      - domain:
          name: "raresociopath.com"
          description: "raresociopath domain"
          specifications:
            - hostnameSpecification:
                includes: "*.raresociopath.com"
        credentials:
          - usernamePassword:
              scope: SYSTEM
              id: rs-docker-hub
              username: raresociopath
              password: ${SUDO_PASSWORD}
unclassified:
  globalLibraries:
    libraries:
      - name: "rs-library"
        defaultVersion: "master"
        implicit: true
        retriever:
          modernSCM:
            scm:
              git:
                remote: "https://github.com/raresociopath/rs-pipelines.git"
                #credentialsId: "no-cred"                
  simple-theme-plugin:
    elements:
      - cssUrl:
          url: "https://raw.githubusercontent.com/raresociopath/rs-pipelines/master/config/theme/rs.css"
