jenkins:
  systemMessage: "RS Jenkins Pipelines"
  numExecutors: 25
  scmCheckoutRetryCount: 10 
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Overall/Read:authenticated"
        - "Overall/Administer:authenticated"
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: admin
          password: admin
credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              scope: GLOBAL
              id: "rs-docker-hub"
              username: "raresociopath"
              password: ${DOCKER_PASSWORD} #Load from Environment Variable
              description: "Username/Password Credentials for docker"          
security:
  globalJobDslSecurityConfiguration:
    useScriptSecurity: false
unclassified:
  globalLibraries:
    libraries:
      - name: "rs-library"
        defaultVersion: "master"
        implicit: true
        retriever:
          modernSCM:
            scm:
              git:
                remote: "https://github.com/raresociopath/rs-pipelines.git"
                #credentialsId: "no-cred"                
  simple-theme-plugin:
    elements:
      - cssUrl:
          url: "https://cdn.rawgit.com/afonsof/jenkins-material-theme/gh-pages/dist/material-indigo.css"