jenkins:
  systemMessage: "RS Jenkins Pipelines"
  numExecutors: 10
  scmCheckoutRetryCount: 10 
  authorizationStrategy:
    roleBased:
      roles:
        global:
          - name: "admin"
            description: "Jenkins administrators"
            permissions:
              - "Overall/Administer"
            assignments:
              - "admin"
          - name: "jenkins-developer"
            description: "Jenkins developers"
            permissions:
              - "Overall/Read"
            assignments:
              - "jenkins-developer"              
          - name: "developers"
            description: "Developers"
            permissions:
              - "Overall/Read"
            assignments:
              - "java-developer"
              - "hello"      
        items:
          - name: "jenkins-dev"
            description: "All jobs needed for development of jobs"
            pattern: (build|internal).*
            permissions:
              - "Job/Read"
              - "Job/Build"
            assignments:
              - "jenkins-developer"        
          - name: "build"
            description: "Jobs in Folder Build"
            pattern: "build.*"
            permissions:
              - "Job/Read"
              - "Job/Build"
            assignments:
              - "java-developer"
              - "hello"
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: admin
          password: admin
        - id: jenkins-developer
          password: jenkins             
        - id: java-developer
          password: java     
credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              scope: GLOBAL
              id: "rs-docker-hub"
              username: "raresociopath"
              password: ${DOCKER_PASSWORD} #Load from Environment Variable
              description: "Username/Password Credentials for docker"          
security:
  globalJobDslSecurityConfiguration:
    useScriptSecurity: false
unclassified:
  globalLibraries:
    libraries:
      - name: "rs-library"
        defaultVersion: "master"
        implicit: true
        retriever:
          modernSCM:
            scm:
              git:
                remote: "https://github.com/raresociopath/rs-pipelines.git"
                #credentialsId: "no-cred"                
  simple-theme-plugin:
    elements:
      - cssUrl:
          url: "https://cdn.rawgit.com/afonsof/jenkins-material-theme/gh-pages/dist/material-indigo.css"