credentials:
  system:
    domainCredentials:
    - credentials:
      - usernamePassword:
          id: "rs-docker-hub"
          password: "{AQAAABAAAAAQUNmCuYHTXetEvuc88FixZS5kESucUnEpK7w5key0i/0=}"
          scope: GLOBAL
          username: "raresociopath"
      domain:
        name: "raresociopath-hub"
        specifications:
        - "dockerServer"
jenkins:
  agentProtocols:
  - "JNLP4-connect"
  - "Ping"
  authorizationStrategy:
    projectMatrix:
      permissions:
      - "Agent/Configure:user"
      - "Agent/Connect:user"
      - "Agent/Create:user"
      - "Agent/Delete:user"
      - "Agent/Disconnect:user"
      - "Job/Build:user"
      - "Job/Cancel:user"
      - "Job/Configure:user"
      - "Job/Create:user"
      - "Job/Delete:user"
      - "Job/Read:user"
      - "Job/Workspace:user"
      - "Overall/Administer:user"
      - "Overall/Read:user"
      - "Run/Delete:user"
      - "Run/Update:user"
      - "SCM/Tag:user"
      - "View/Configure:user"
      - "View/Create:user"
      - "View/Delete:user"
      - "View/Read:user"
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  disableRememberMe: false
  globalNodeProperties:
  - envVars:
      env:
      - key: "SCM_CLONE_METHOD"
        value: "https"
      - key: "SCM_SERVER"
        value: "github.com"
      - key: "SHELL"
        value: "/bin/bash"
  markupFormatter:
    rawHtml:
      disableSyntaxHighlighting: false
  mode: NORMAL
  myViewsTabBar: "standard"
  numExecutors: 2
  primaryView:
    all:
      description: "Hello World Jenkins"
      name: "all"
  projectNamingStrategy: "standard"
  quietPeriod: 5
  remotingSecurity:
    enabled: true
  scmCheckoutRetryCount: 0
  securityRealm:
    local:
      allowsSignup: true
      enableCaptcha: false
      users:
      - id: "test"
      - id: "user"
  slaveAgentPort: -1
  updateCenter:
    sites:
    - id: "default"
      url: "https://updates.jenkins.io/update-center.json"
  views:
  - all:
      description: "Hello World Jenkins"
      name: "all"
  - list:
      columns:
      - "status"
      - "weather"
      - "jobName"
      - "lastSuccess"
      - "lastFailure"
      - "lastDuration"
      - "buildButton"
      name: "test"
      recurse: true
  viewsTabBar: "standard"
security:
  apiToken:
    creationOfLegacyTokenEnabled: false
    tokenGenerationOnCreationEnabled: false
    usageStatisticsEnabled: true
  downloadSettings:
    useBrowser: false
  envInject:
    enableLoadingFromMaster: false
    enablePermissions: false
    hideInjectedVars: false
  globalJobDslSecurityConfiguration:
    useScriptSecurity: false
  sSHD:
    port: -1
  scriptApproval:
    approvedSignatures:
    - "method hudson.model.Saveable save"
    - "method jenkins.model.Jenkins getExtensionList java.lang.Class"
    - "method org.codefirst.SimpleThemeDecorator setElements java.util.List"
    - "new org.jenkinsci.plugins.simpletheme.CssUrlThemeElement java.lang.String"
    - "staticMethod jenkins.model.Jenkins getInstance"
unclassified:
  ansiColorBuildWrapper:
    colorMaps:
    - black: "#000000"
      blackB: "#4C4C4C"
      blue: "#1E90FF"
      blueB: "#4682B4"
      cyan: "#00CDCD"
      cyanB: "#00FFFF"
      green: "#00CD00"
      greenB: "#00FF00"
      magenta: "#CD00CD"
      magentaB: "#FF00FF"
      name: "xterm"
      red: "#CD0000"
      redB: "#FF0000"
      white: "#E5E5E5"
      whiteB: "#FFFFFF"
      yellow: "#CDCD00"
      yellowB: "#FFFF00"
    - black: "#000000"
      blackB: "#555555"
      blue: "#0000AA"
      blueB: "#5555FF"
      cyan: "#00AAAA"
      cyanB: "#55FFFF"
      defaultBackground: 0
      defaultForeground: 7
      green: "#00AA00"
      greenB: "#55FF55"
      magenta: "#AA00AA"
      magentaB: "#FF55FF"
      name: "vga"
      red: "#AA0000"
      redB: "#FF5555"
      white: "#AAAAAA"
      whiteB: "#FFFFFF"
      yellow: "#AA5500"
      yellowB: "#FFFF55"
    - black: "black"
      blackB: "black"
      blue: "blue"
      blueB: "blue"
      cyan: "cyan"
      cyanB: "cyan"
      green: "green"
      greenB: "green"
      magenta: "magenta"
      magentaB: "magenta"
      name: "css"
      red: "red"
      redB: "red"
      white: "white"
      whiteB: "white"
      yellow: "yellow"
      yellowB: "yellow"
    - black: "#2E3436"
      blackB: "#2E3436"
      blue: "#3465A4"
      blueB: "#3465A4"
      cyan: "#06989A"
      cyanB: "#06989A"
      defaultBackground: 0
      defaultForeground: 7
      green: "#4E9A06"
      greenB: "#4E9A06"
      magenta: "#75507B"
      magentaB: "#75507B"
      name: "gnome-terminal"
      red: "#CC0000"
      redB: "#CC0000"
      white: "#D3D7CF"
      whiteB: "#D3D7CF"
      yellow: "#C4A000"
      yellowB: "#C4A000"
  buildStepOperation:
    enabled: true
  extendedEmailPublisher:
    adminRequiredForTemplateTesting: false
    allowUnregisteredEnabled: false
    charset: "UTF-8"
    debugMode: false
    defaultBody: "$PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS:\r\n\r\nCheck\
      \ console output at $BUILD_URL to view the results."
    defaultContentType: "text/plain"
    defaultSubject: "$PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS!"
    maxAttachmentSize: -1
    maxAttachmentSizeMb: 0
    precedenceBulk: false
    useSsl: false
    watchingEnabled: false
  gitHubPluginConfig:
    hookUrl: "http://35.177.1.81/jenkins/github-webhook/"
  gitSCM:
    createAccountBasedOnEmail: false
    showEntireCommitSummaryInChanges: false
    useExistingAccountWithSameEmail: false
  globalLibraries:
    libraries:
    - defaultVersion: "master"
      implicit: true
      name: "rs-pipelines"
      retriever:
        modernSCM:
          scm:
            git:
              id: "60bec656-20d5-4cfc-8de7-398cbec3068c"
              remote: "https://github.com/raresociopath/rs-pipelines.git"
              traits:
              - "gitBranchDiscovery"
  location:
    adminAddress: "address not configured yet <nobody@nowhere>"
    url: "http://35.177.1.81/jenkins/"
  mailer:
    charset: "UTF-8"
    useSsl: false
  pollSCM:
    pollingThreadCount: 10
  simple-theme-plugin:
    elements:
      - cssUrl: 
          url: "https://fishi.devtail.io/content-images/jenkins-devtail-theme.css"
  timestamperConfig:
    allPipelines: false
    elapsedTimeFormat: "'<b>'HH:mm:ss.S'</b> '"
    systemTimeFormat: "'<b>'HH:mm:ss'</b> '"
tool:
  dockerTool:
    installations:
    - name: "docker"
      properties:
      - installSource:
          installers:
          - docker:
              version: "latest"
  git:
    installations:
    - home: "/opt/bitnami/git/bin/git"
      name: "Default"
  gradle:
    installations:
    - home: "/opt/bitnami/gradle"
      name: "Default"
