jenkins:
  systemMessage: "RS TEST"
  numExecutors: 25
  scmCheckoutRetryCount: 10 
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Overall/Read:authenticated"
        - "Overall/Administer:authenticated"
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: admin
          password: admin
credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              scope: GLOBAL
              id: "rs-docker-hub"
              username: "raresociopath"
              password: ${DOCKER_PASSWORD} #Load from Environment Variable
              description: "Username/Password Credentials for docker"          
security:
  globalJobDslSecurityConfiguration:
    useScriptSecurity: false
unclassified:
  globalLibraries:
    libraries:
      - name: "rs-library"
        defaultVersion: "master"
        implicit: true
        retriever:
          modernSCM:
            scm:
              git:
                remote: "https://github.com/raresociopath/rs-pipelines.git"
                #credentialsId: "no-cred"                
  simple-theme-plugin:
    elements:
      - cssUrl:
          url: "https://cdn.rawgit.com/afonsof/jenkins-material-theme/gh-pages/dist/material-green.css"
groovy:
  - script: >
      import jenkins.model.Jenkins;

      def signatures = [
              'staticMethod jenkins.model.Jenkins get',
              'method jenkins.model.Jenkins getExtensionList java.lang.String',
              'method org.jenkinsci.plugins.scriptsecurity.scripts.ScriptApproval approveSignature java.lang.String'
      ]

      def scriptApproval = Jenkins.get().getExtensionList("org.jenkinsci.plugins.scriptsecurity.scripts.ScriptApproval")[0]
      signatures.each {
          scriptApproval.approveSignature(it)
      }
