jenkins:
  systemMessage: "RS Jenkins Pipelines"
  numExecutors: 25
  scmCheckoutRetryCount: 10 
  authorizationStrategy:
    roleBased:
      roles:
        global:
          - name: "admin"
            description: "Jenkins administrators"
            permissions:
              - "Overall/Administer"
            assignments:
              - "admin"
          - name: "readonly"
            description: "Read-only users"
            permissions:
              - "Overall/Read"
              - "Job/Read"
            assignments:
              - "authenticated"
        items:
          - name: "build"
            description: "Jobs in Folder A, but not the folder itself"
            pattern: "build/.*"
            permissions:
              - "Job/Build"
            assignments:
              - "test"
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: admin
          password: admin
        - id: test
          password: test          
credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              scope: GLOBAL
              id: "rs-docker-hub"
              username: "raresociopath"
              password: ${DOCKER_PASSWORD} #Load from Environment Variable
              description: "Username/Password Credentials for docker"          
security:
  globalJobDslSecurityConfiguration:
    useScriptSecurity: false
unclassified:
  globalLibraries:
    libraries:
      - name: "rs-library"
        defaultVersion: "master"
        implicit: true
        retriever:
          modernSCM:
            scm:
              git:
                remote: "https://github.com/raresociopath/rs-pipelines.git"
                #credentialsId: "no-cred"                
  simple-theme-plugin:
    elements:
      - cssUrl:
          url: "https://cdn.rawgit.com/afonsof/jenkins-material-theme/gh-pages/dist/material-indigo.css"