jenkins:
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: ion
          password: ion

  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Overall/Read:anonymous"
        - "Overall/Administer:authenticated"
security:
  globalJobDslSecurityConfiguration:
    useScriptSecurity: false         
unclassified:
  globalLibraries:
    libraries:
      - name: "awesome-lib"
        retriever:
          modernSCM:
            scm:
              git:
                remote: "https://github.com/raresociopath/rs-pipelines.git"
                #credentialsId: "no-cred"                
  simple-theme-plugin:
    elements:
      - cssUrl:
          url: "${HUDSON_URL}/userContent/rs.css"
